name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t bi-backend:${{ github.sha }} ./backend/django_app
          docker build -t bi-fastapi:${{ github.sha }} ./backend/fastapi_app
          docker build -t bi-frontend:${{ github.sha }} ./frontend/vue_app

          


      - name: Save Docker image
        run: |
           docker save bi-backend:${{ github.sha }} bi-fastapi:${{ github.sha }} bi-frontend:${{ github.sha }} | gzip > images.tar.gz

      - name: Verify image archive
        run: |
          ls -lah images.tar.gz
          tar -tf images.tar.gz


      - name: Ensure target dir exists on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:      
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /opt/BI

      - name: Upload images.tar.gz to VPS
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

          scp -i key.pem -o StrictHostKeyChecking=no images.tar.gz \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/BI/images.tar.gz

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:      
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/BI

            docker load < images.tar.gz

            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ github.sha }}/" .env || echo "IMAGE_TAG=${{ github.sha }}" >> .env


            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d   