name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t bi-backend:${{ github.sha }} ./backend/django_app
          docker build -t bi-fastapi:${{ github.sha }} ./backend/fastapi_app
          docker build -t bi-frontend:${{ github.sha }} ./frontend/vue_app

      - name: Save Docker image
        run: |
           docker save bi-backend:${{ github.sha }} bi-fastapi:${{ github.sha }} bi-frontend:${{ github.sha }} | gzip > images.tar.gz

      - name: Verify saved image
        run: |
          echo "workspace:"
          pwd
          ls -la /github/workspace

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "/github/workspace/images.tar.gz"
          target: "/root/BI"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/BI
            docker load < image.tar.gz
            export IMAGE_TAG=${{ github.sha }}
            docker compose -f docker-compose.prod.yml up -d --force-recreate
